### ISSUE TITLE
Right-clicking the organization bar for the torrent list shows the context menu for the selected torrent.

### ISSUE THREAD

**Issue by mornite** [ddevault/Patchy#62]
I recommend having this action display a menu to show or hide fields in the torrent list, like it does in uTorrent.

![screenshot](https://f.cloud.github.com/assets/1310872/168119/f46d4578-79f0-11e2-8ff7-758d66d232d8.png)

**Comment by ddevault** [comment]
I can fix this so it doesn't show the context menu, but the ability to change which columns show may be delayed to post-launch.

**Comment by ddevault** [comment]
Also, I suggest in future bug reports, you black out information that is not relevant to the bug. I've taken care of it for you, but try to do so yourself in the future.

**Comment by mornite** [comment]
Ok. Normally I would, but there was nothing there I would consider "worth hiding".

**Comment by ddevault** [comment]
Indeed, I simply prefer a widespread blackout on such things, considering the potential nefarious uses for Patchy.

**Comment by ddevault** [comment]
Wow, this bug is a pain in the ass to fix.
