### ISSUE TITLE
Incoming port can be set to invalid values

### ISSUE THREAD

**Issue by pdelvo** [ddevault/Patchy#74]
If you set the Incoming port to e.g. -5 Patchy will not longer start. 

Ausnahmeinformationen: System.ArgumentOutOfRangeException
Stapel:
   bei System.Net.IPEndPoint..ctor(System.Net.IPAddress, Int32)
   bei MonoTorrent.Client.ClientEngine..ctor(MonoTorrent.Client.EngineSettings, MonoTorrent.Client.PeerListener, MonoTorrent.Client.PieceWriters.PieceWriter)
   bei MonoTorrent.Client.ClientEngine..ctor(MonoTorrent.Client.EngineSettings, MonoTorrent.Client.PieceWriters.PieceWriter)
   bei MonoTorrent.Client.ClientEngine..ctor(MonoTorrent.Client.EngineSettings)
   bei Patchy.ClientManager.Initialize(Patchy.SettingsManager)
   bei Patchy.MainWindow.Initialize()
   bei Patchy.MainWindow..ctor()
   bei Patchy.App.OnStartup(System.Windows.StartupEventArgs)
   bei System.Windows.Application.<.ctor>b__1(System.Object)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   bei MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
   bei System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   bei System.Windows.Threading.DispatcherOperation.Invoke()
   bei System.Windows.Threading.Dispatcher.ProcessQueue()
   bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   bei MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   bei MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   bei System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   bei System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   bei System.Windows.Threading.Dispatcher.Run()
   bei System.Windows.Application.RunDispatcher(System.Object)
   bei System.Windows.Application.RunInternal(System.Windows.Window)
   bei System.Windows.Application.Run(System.Windows.Window)
   bei System.Windows.Application.Run()
   bei Patchy.App.Main()

**Comment by ddevault** [comment]
By the way, if you need a fix (because your Patchy can't start), look in `%appdata%\.patchy\settings` (text file) and change it manually.

**Comment by pdelvo** [comment]
I did this

**Comment by ddevault** [comment]
Closed in d67a611684e5ccdfe7bd8d5b6f7ef5c45e072f42
