### ISSUE TITLE
Painless transfer from popular clients

### ISSUE THREAD

**Issue by ghost** [ddevault/Patchy#75]
I would love to be able to import all my torrents from utorrent. My main problem is the data is not all in the same directory so I couldn't just use a watch folder or similar. Also I don't particularly want to recheck hundreds of torrents. This is basically the only reason I still use utorrent (2.2.1)

http://forum.utorrent.com/viewtopic.php?pid=181858#p181858 has some info on resume.dat for utorrent.

**Comment by ddevault** [comment]
This is planned to be included in the installer. Thanks for making mention of it.

**Comment by ddevault** [comment]
Here's the information I've gathered so far:
- Deluge has some weird format that's stored in `%appdata%\deluge\torrents.state`, and I've yet to decipher it.
- uTorrent stores a BEncodedDictionary at `%appdata%\uTorrent\resume.dat`, that will be easy to support. Torrent files are stored in `%appdata%\uTorrent\*.torrent`.
- Transmission stores sevral BEncodedDictionaries in `%appdata%\transmission\Resume\`. Corresponding torrent files are kept in `%appdata%\transmission\Torrents\`.

**Comment by ddevault** [comment]
![screenshot](https://f.cloud.github.com/assets/1310872/190784/ff5f3e96-7f0e-11e2-826b-6ee641a87130.png)

^_^
